name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: _build
        key: ${{ runner.os }}-elixir-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-elixir-
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Test
      run: mix test --cover --trace
    - name: Formatted?
      run: mix format --check-formatted --dry-run
    - name: Credo
      run: mix credo --verbose
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
